name: build
on: [pull_request]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build and Run Tests
        run: ./gradlew testDebugUnitTest
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'